services:
  jellysay:
    build:
      context: .
    ports:
      - "3535:3535"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      JELLYFIN_BASE_URL: ${JELLYFIN_BASE_URL}
      JELLYFIN_API_KEY: ${JELLYFIN_API_KEY}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      EPISODE_PREMIERED_WITHIN_X_DAYS: ${EPISODE_PREMIERED_WITHIN_X_DAYS}
      SEASON_ADDED_WITHIN_X_DAYS: ${SEASON_ADDED_WITHIN_X_DAYS}
    volumes:
      - ./data:/app/data
      - ./log:/app/log